pipeline {
    agent {
        label "master || built-in"
    }

    stages {
        stage('Build') {
            steps {
                sh("echo Hello World from JNLP")
            }
        }
    }
}
